site_name: Labs4grabs.io Docs
site_url: https://docs.labs4grabs.io/
use_directory_urls: false
repo_url: https://github.com/labs4grabs/docs

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - search
  - mike:
      canonical_version: null
      version_selector: true

copyright: |
  For support reach out via 
  <a 
    href="mailto:info@labs4grabs.io"
    onmouseover="this.href=this.href.replace(',', '.')">
    info@labs4grabs.io
  </a>

theme:
  name: material
  font:
    text: Roboto
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github

nav:
  - Getting started: index.md
  - Windows: windows.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://labs4grabs.slack.com/
    - icon: fontawesome/brands/github
      link: https://github.com/labs4grabs
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/stefanroman
    - icon: fontawesome/solid/globe
      link: https://labs4grabs.io/
